---
kind: pipeline
type: kubernetes
name: deploy prod
trigger:
  event:
    - push
  branch:
    - main

steps:

  - &deploy
    name: cs-prod
    image: quay.io/ukhomeofficedigital/hocs-helm-kubectl:1.1.0
    environment:
      KUBE_CLUSTER: acp-prod
      KUBE_NAMESPACE: cs-prod
      KUBE_SERVER: https://kube-api-prod.prod.acp.homeoffice.gov.uk
      KUBE_TOKEN:
        from_secret: cs_prod
      ALLOWED_IPS:
        from_secret: ALLOWED_IPS
      RDS_CIDR:
        from_secret: RDS_CIDR
    commands:
      - bash -x helmfile-deploy.sh

  - <<: *deploy
    name: wcs-prod
    environment:
      KUBE_NAMESPACE: wcs-prod
    depends_on:
      - cs-prod
