---
kind: pipeline
type: kubernetes
name: deploy uat migration
trigger:
  event:
    - push
  branch:
    - main

steps:

  - name: cs-uat-migration
    image: quay.io/ukhomeofficedigital/hocs-helm-kubectl:1.1.0
    environment:
      KUBE_CLUSTER: acp-prod
      KUBE_NAMESPACE: cs-uat-migration
      KUBE_SERVER: https://kube-api-prod.prod.acp.homeoffice.gov.uk
      KUBE_TOKEN:
        from_secret: cs_prod_migration
      ALLOWED_IPS:
        from_secret: ALLOWED_IPS
      RDS_CIDR:
        from_secret: RDS_CIDR
      AWS_ACCOUNT:
        from_secret: AWS_ACCOUNT
    commands:
      - bash -x helmfile-deploy.sh
